// Code generated by internal/gen. DO NOT EDIT.
package models

type Minutely15UnitsResponse struct {
	Time *string `json:"time,omitempty"`
	Temperature2M *string `json:"temperature_2m,omitempty"`
	RelativeHumidity2M *string `json:"relative_humidity_2m,omitempty"`
	DewPoint2M *string `json:"dew_point_2m,omitempty"`
	ApparentTemperature *string `json:"apparent_temperature,omitempty"`
	Precipitation *string `json:"precipitation,omitempty"`
	Rain *string `json:"rain,omitempty"`
	Snowfall *string `json:"snowfall,omitempty"`
	SnowfallHeight *string `json:"snowfall_height,omitempty"`
	FreezingLevelHeight *string `json:"freezing_level_height,omitempty"`
	SunshineDuration *string `json:"sunshine_duration,omitempty"`
	WeatherCode *string `json:"weather_code,omitempty"`
	WindSpeed10M *string `json:"wind_speed_10m,omitempty"`
	WindSpeed80M *string `json:"wind_speed_80m,omitempty"`
	WindDirection10M *string `json:"wind_direction_10m,omitempty"`
	WindDirection80M *string `json:"wind_direction_80m,omitempty"`
	WindGusts10M *string `json:"wind_gusts_10m,omitempty"`
	Visibility *string `json:"visibility,omitempty"`
	Cape *string `json:"cape,omitempty"`
	LightningPotential *string `json:"lightning_potential,omitempty"`
	IsDay *string `json:"is_day,omitempty"`
	ShortwaveRadiation *string `json:"shortwave_radiation,omitempty"`
	DirectRadiation *string `json:"direct_radiation,omitempty"`
	DirectNormalIrradiance *string `json:"direct_normal_irradiance,omitempty"`
	DiffuseRadiation *string `json:"diffuse_radiation,omitempty"`
	GlobalTiltedIrradiance *string `json:"global_tilted_irradiance,omitempty"`
	TerrestrialRadiation *string `json:"terrestrial_radiation,omitempty"`
	ShortwaveRadiationInstant *string `json:"shortwave_radiation_instant,omitempty"`
	DirectRadiationInstant *string `json:"direct_radiation_instant,omitempty"`
	DirectNormalIrradianceInstant *string `json:"direct_normal_irradiance_instant,omitempty"`
	DiffuseRadiationInstant *string `json:"diffuse_radiation_instant,omitempty"`
	GlobalTiltedIrradianceInstant *string `json:"global_tilted_irradiance_instant,omitempty"`
	TerrestrialRadiationInstant *string `json:"terrestrial_radiation_instant,omitempty"`
}

type Minutely15WeatherResponse struct {
	Time []string `json:"time,omitempty"`
	Temperature2M []float32 `json:"temperature_2m,omitempty"`
	RelativeHumidity2M []float32 `json:"relative_humidity_2m,omitempty"`
	DewPoint2M []float32 `json:"dew_point_2m,omitempty"`
	ApparentTemperature []float32 `json:"apparent_temperature,omitempty"`
	Precipitation []float32 `json:"precipitation,omitempty"`
	Rain []float32 `json:"rain,omitempty"`
	Snowfall []float32 `json:"snowfall,omitempty"`
	SnowfallHeight []float32 `json:"snowfall_height,omitempty"`
	FreezingLevelHeight []float32 `json:"freezing_level_height,omitempty"`
	SunshineDuration []float32 `json:"sunshine_duration,omitempty"`
	WeatherCode []int `json:"weather_code,omitempty"`
	WindSpeed10M []float32 `json:"wind_speed_10m,omitempty"`
	WindSpeed80M []float32 `json:"wind_speed_80m,omitempty"`
	WindDirection10M []int `json:"wind_direction_10m,omitempty"`
	WindDirection80M []int `json:"wind_direction_80m,omitempty"`
	WindGusts10M []float32 `json:"wind_gusts_10m,omitempty"`
	Visibility []float32 `json:"visibility,omitempty"`
	Cape []float32 `json:"cape,omitempty"`
	LightningPotential []float32 `json:"lightning_potential,omitempty"`
	IsDay []int `json:"is_day,omitempty"`
	ShortwaveRadiation []float32 `json:"shortwave_radiation,omitempty"`
	DirectRadiation []float32 `json:"direct_radiation,omitempty"`
	DirectNormalIrradiance []float32 `json:"direct_normal_irradiance,omitempty"`
	DiffuseRadiation []float32 `json:"diffuse_radiation,omitempty"`
	GlobalTiltedIrradiance []float32 `json:"global_tilted_irradiance,omitempty"`
	TerrestrialRadiation []float32 `json:"terrestrial_radiation,omitempty"`
	ShortwaveRadiationInstant []float32 `json:"shortwave_radiation_instant,omitempty"`
	DirectRadiationInstant []float32 `json:"direct_radiation_instant,omitempty"`
	DirectNormalIrradianceInstant []float32 `json:"direct_normal_irradiance_instant,omitempty"`
	DiffuseRadiationInstant []float32 `json:"diffuse_radiation_instant,omitempty"`
	GlobalTiltedIrradianceInstant []float32 `json:"global_tilted_irradiance_instant,omitempty"`
	TerrestrialRadiationInstant []float32 `json:"terrestrial_radiation_instant,omitempty"`
}
